### ISSUE TITLE
returning a value in demo.re

### ISSUE THREAD

**Issue by idkjs** [ahrefs/bs-dotenv#2]
I've tried the following but seem to be missing something in syntax.

```
Dotenv.config();

/* let _ = Js.log(Node.Process.process##env.VALUE1); */ doesnt work
/* let _ = Js.log(Node.Process.process##env##VALUE1); */ doesnt work
let x = Node.Process.process##env;

let _ = Js.log(x.VALUE1); // throws error

let _ = Js.log(Node.Process.process##env); // works
```

Thanks for any guidance

**Comment by Khady** [comment]
`Node.Process.process##env` is of type `Js.Dict.t(string)`. So you want to use `Js.Dict.get` or `Js.Dict.unsafeGet` on it.

```reason
Js.Dict.unsafeGet(Node.Process.process##env, "VALUE1")
```

**Comment by Khady** [comment]
Follow up on https://reasonml.chat/t/decifering-type-error-message/484
